### PR TITLE
Create a nav-mobile and Data/update nav-bar and layout

### PR DESCRIPTION
**Pull request by danilomartinss**
Created the files nav-mobile.tsx and navData.ts

nav-mobile.tsx contains the logic for displaying the hamburger menu on mobile devices
navData.ts stores the menu data for both nav-mobile.tsx and nav-bar.tsx
Updated nav-bar.tsx to use navData.ts

Updated layout.tsx to toggle between using nav-bar and nav-mobile

Note: Some pages need to be manually adjusted, which will be done in the Update-content branch

### CODE REVIEW

**Comment by joshbaskaran** [comment]
Looks like you forgot to commit the `package.json` and the `pnpm-lock.yml` files. The error is a build error which can't resolve `hamburger-react`.

**Comment by joshbaskaran** [comment]
@danilomartinss 
This is mostly alright but needs a few adjustments:
1. It's better to put the burger menu on the left side and to accommodate that, move the logo to the center on mobile screens.
2. The menu doesn't render properly in dark mode, it's needs colour adjustments
3. The links should change the cursor to pointers.
4. The sub menus should also appear here.
5. In terms of design, it looks out of place when compares to the rest of the website. It's rather flat and should be generally in line with the rest of the webpage design.

**Comment by danilomartinss** [comment]
> @danilomartinss This is mostly alright but needs a few adjustments:
> 
> 1. It's better to put the burger menu on the left side and to accommodate that, move the logo to the center on mobile screens.
> 2. The menu doesn't render properly in dark mode, it's needs colour adjustments
> 3. The links should change the cursor to pointers.
> 4. The sub menus should also appear here.
> 5. In terms of design, it looks out of place when compares to the rest of the website. It's rather flat and should be generally in line with the rest of the webpage design.

The numbers 1,2 and 5 are done

**Comment by joshbaskaran** [comment]
> If you have any suggestions for changes, I will be happy to change them. Thank you

Try this: https://ui.shadcn.com/docs/components/sheet

**Comment by joshbaskaran** [comment]
Implemented in f17b85bbede10090ca8b1ec0fc88c01efa0e3322

**Pull request closed without merging**
